matrix:
  include:
  - language: python
    name: Project lint, generation tests and build
    python:
    - '2.7'
    install:
    - python -m pip install --requirement tools/generation/requirements.txt
    - python -m pip install --requirement tools/lint/requirements.txt
    script:
    - "./tools/scripts/ci_build.sh"
    - "./tools/generation/test/run.py"
    - "./tools/lint/test/run.py"
    - "./tools/scripts/ci_lint.sh"
    after_success:
    - "./tools/scripts/deploy.sh"
  - language: node_js
    name: New or modified tests
    if: type = pull_request
    node_js: node
    before_script: jsvu --os=linux64 --engines=all
    script: "./tools/scripts/ci_test.js"
  allow_failures:
  - name: New or modified tests
notifications:
  webhooks:
  - https://www.travisbuddy.com/
travisBuddy:
  regex: "(Summary for tests execution:[\s\S]*End of summary!)"
  insertMode: update
  successBuildLog: true
